### PR TITLE
Add f0rmiga as approver to OWNERS

### PR DESCRIPTION
**Pull request by f0rmiga**

### CODE REVIEW

**Comment by carolynvs** [comment]
Yay!

**Comment by f0rmiga** [comment]
@carolynvs Thanks!

**Comment by f0rmiga** [comment]
@carolynvs I think it's just pending removing the netlify webhook, then tide will be able to merge. :)

**Comment by carolynvs** [comment]
I'm not sure how to remove it. I don't have admin rights on the repo now that it is in this org. @nikhita Sorry to bug you, do you have admin rights on this repo now? I can't remove the webhook for netlify. 😀

**Comment by nikhita** [comment]
Webhook removed. 

Btw you might also want to set travis as a required status for Tide, like https://github.com/kubernetes/test-infra/blob/68705d20619c6f0116590e274cff2bb7f31c0321/prow/config.yaml#L258-L262, or maybe even move to prow :stuck_out_tongue: 

/skip

**Comment by nikhita** [comment]
I think skip only works on prowjobs, org owners can override contexts using `/override` but that plugin hasn't be enabled here yet. I'd prefer not to enable that plugin unless _really_ needed. 

@f0rmiga can you force push again, that should probably remove the netlify check...

**Comment by nikhita** [comment]
/hold

@f0rmiga you'll only be able to actually approve PRs if you are a @kubernetes-sigs org member. You can apply for membership by creating an issue [here](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E).

You'll also need two sponsors for the membership application. Feel free to add me as one of the sponsors, and I think I can speak for @carolynvs that she'd be happy to do the same as well. :smile:

**Comment by f0rmiga** [comment]
@nikhita I've done the membership request. Thanks for sponsoring me!

**Comment by f0rmiga** [comment]
@nikhita I got the membership!

**Pull request merged**
